/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AionisAgentManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AionisAgentManager__factory>;
    getContractFactory(
      name: "IAlgebraRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAlgebraRouter__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ISomniaAgentPlatform",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISomniaAgentPlatform__factory>;
    getContractFactory(
      name: "FollowerRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FollowerRegistry__factory>;
    getContractFactory(
      name: "SomniaGreeting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SomniaGreeting__factory>;
    getContractFactory(
      name: "IAlgebraRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAlgebraRouter__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ISomniaAgentPlatform",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISomniaAgentPlatform__factory>;
    getContractFactory(
      name: "StellalphaAgentManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StellalphaAgentManager__factory>;

    getContractAt(
      name: "AionisAgentManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AionisAgentManager>;
    getContractAt(
      name: "IAlgebraRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAlgebraRouter>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ISomniaAgentPlatform",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISomniaAgentPlatform>;
    getContractAt(
      name: "FollowerRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FollowerRegistry>;
    getContractAt(
      name: "SomniaGreeting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SomniaGreeting>;
    getContractAt(
      name: "IAlgebraRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAlgebraRouter>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ISomniaAgentPlatform",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISomniaAgentPlatform>;
    getContractAt(
      name: "StellalphaAgentManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StellalphaAgentManager>;

    deployContract(
      name: "AionisAgentManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AionisAgentManager>;
    deployContract(
      name: "IAlgebraRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAlgebraRouter>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISomniaAgentPlatform",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaAgentPlatform>;
    deployContract(
      name: "FollowerRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FollowerRegistry>;
    deployContract(
      name: "SomniaGreeting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaGreeting>;
    deployContract(
      name: "IAlgebraRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAlgebraRouter>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISomniaAgentPlatform",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaAgentPlatform>;
    deployContract(
      name: "StellalphaAgentManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StellalphaAgentManager>;

    deployContract(
      name: "AionisAgentManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AionisAgentManager>;
    deployContract(
      name: "IAlgebraRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAlgebraRouter>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISomniaAgentPlatform",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaAgentPlatform>;
    deployContract(
      name: "FollowerRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FollowerRegistry>;
    deployContract(
      name: "SomniaGreeting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaGreeting>;
    deployContract(
      name: "IAlgebraRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAlgebraRouter>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISomniaAgentPlatform",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaAgentPlatform>;
    deployContract(
      name: "StellalphaAgentManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StellalphaAgentManager>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
