/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aionisAgentManagerSol from "./AionisAgentManager.sol";
export type { aionisAgentManagerSol };
import type * as stellalphaAgentManagerSol from "./StellalphaAgentManager.sol";
export type { stellalphaAgentManagerSol };
export type { FollowerRegistry } from "./FollowerRegistry";
export type { SomniaGreeting } from "./SomniaGreeting";
export * as factories from "./factories";
export type { AionisAgentManager } from "./AionisAgentManager.sol/AionisAgentManager";
export { AionisAgentManager__factory } from "./factories/AionisAgentManager.sol/AionisAgentManager__factory";
export type { IAlgebraRouter } from "./AionisAgentManager.sol/IAlgebraRouter";
export { IAlgebraRouter__factory } from "./factories/AionisAgentManager.sol/IAlgebraRouter__factory";
export type { IERC20 } from "./AionisAgentManager.sol/IERC20";
export { IERC20__factory } from "./factories/AionisAgentManager.sol/IERC20__factory";
export type { ISomniaAgentPlatform } from "./AionisAgentManager.sol/ISomniaAgentPlatform";
export { ISomniaAgentPlatform__factory } from "./factories/AionisAgentManager.sol/ISomniaAgentPlatform__factory";
export { FollowerRegistry__factory } from "./factories/FollowerRegistry__factory";
export { SomniaGreeting__factory } from "./factories/SomniaGreeting__factory";
export type { StellalphaAgentManager } from "./StellalphaAgentManager.sol/StellalphaAgentManager";
export { StellalphaAgentManager__factory } from "./factories/StellalphaAgentManager.sol/StellalphaAgentManager__factory";
