/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aionisAgentManagerSol from "./AionisAgentManager.sol";
export type { aionisAgentManagerSol };
export type { FollowerRegistry } from "./FollowerRegistry";
export type { SomniaGreeting } from "./SomniaGreeting";
export type { AUSD } from "./AUSD";
export type { AUSDC } from "./AUSDC";
